### ISSUE TITLE
Suggestions for README.md

### ISSUE THREAD

**Issue by NgHongJie** [jdbancal/libtrevisan#1]
Hi Jean-Daniel,

I think the README.md file can be improved slightly! For example, in the line

>  Installation commands are provided below for ubuntu-type systems.

You could add that it will not work for ubuntu systems that are 16.04 and before. (I have not tried 18.04 onwards but I know that it works for 19.10) 

In addition, in this line,

>gf2x, install with the commands `./configure`, `make`, `make check`, `sudo make install` within the downloaded folder

I think you can add that users should try executing `sudo ldconfig`  in their terminal after `sudo make install` as by default, unix does not look in usr/local/lib for libraries, but that is where the gf2x library is installed. Hence, if we were to execute a `make check` for the NTL library without `sudo ldconfig`, it would return an error more often than not.

I hope my suggestions helped! :)

Cheers,
Hong Jie

**Comment by jdbancal** [comment]
Fixed in e31af51d37189c72eb3a998d8e2900c271befcd0
