### ISSUE TITLE
After Compiling

### ISSUE THREAD

**Issue by apassenger** [jdbancal/libtrevisan#2]
Hello
I have 2 questions
1)when I run make command I had too many warnings regarding the code syntax, I could not see errors but I dont kno it will effect my code or not
![Screenshot from 2020-12-07 01-45-46](https://user-images.githubusercontent.com/25195538/101298581-0ac17100-382f-11eb-9a46-17310ba60ad6.png)
![Screenshot from 2020-12-07 01-45-59](https://user-images.githubusercontent.com/25195538/101298583-0b5a0780-382f-11eb-8f7d-4c0e7aa83907.png)
![Screenshot from 2020-12-07 01-46-10](https://user-images.githubusercontent.com/25195538/101298584-0bf29e00-382f-11eb-9b72-b045a3191dd7.png)
![Screenshot from 2020-12-07 01-46-18](https://user-images.githubusercontent.com/25195538/101298585-0c8b3480-382f-11eb-8064-0469ee408194.png)

2)I could compile code and after compling I could have extractor file and gen_irreps but after that how can I run the code Can you explain it? Which command or how??
Thanks for helps

**Comment by jdbancal** [comment]
Hi @apassenger ,

1) Warnings are ok. The language changes, so a new compiler will produce warnings when some features become depreciated for instance. When they are not working anymore, the compiler will produce an error. Hence, this shows that the code could be improved to the new standard.

2) Did you try asking the program for help? In a terminal, you can do this by typing `./extractor --help`. This will show you all the possible options in which you can use the program.

    In order to use the extractor correctly, you should understand the theory behind it. The basic theory is presented in the following paper: [A modular framework for randomness extraction based on Trevisan's construction](https://arxiv.org/abs/1212.0520)

    If you just want to run a test extraction, you can use something along the lines of the following command, which was used for [arXiv:1805.02828](https://www.arxiv.org/abs/1805.02828):
    ```
    ./extractor -v --Blk_Design --bitext rsh --eps 7.131115008135518e-20 --alpha 0.001763415230047004 --weakdes gfp --outputsize 617950 --inputsize 350576312 --seed seed.txt --input source.txt --output_file output.txt
    ```
    Note that the exact number you want to put here depend on the data you are providing (e.g. how many bits should be read, and how many bits should be extracted). Also note that in this example alpha*inputsize ~ outputsize. Don't be afraid of trying some parameters, the code should just tell you if the seed is too short for what you are asking for, or if you put some incompatible parameters.
