### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by apassenger** [jdbancal/libtrevisan#3]
Hello,

First, Thank you very much for your previous answer and I tried to play with parameters. When I have insufficient seed file, program tells me that. However when the files are ok, this time I am getting "Aborted(core dumped)" message and my output file can not be created. I mean no error but no output file too.

What can I do with this problem? 
Here is my screenshot
![Screenshot from 2020-12-09 10-42-12](https://user-images.githubusercontent.com/25195538/101613448-0ef6b580-3a0c-11eb-88eb-d11811fea4ec.png)
Thank you very much!

**Comment by apassenger** [comment]
And sometimes I am getting this:
terminate called recursively
  what():  vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)
Aborted (core dumped)
When I play with parameters, I can skip this error but I cannot fix the aborted core dumped..

**Comment by jdbancal** [comment]
Do your input files contain only `0` and `1` characters? (plus eventually a newline character after every 80 symbols)?

**Comment by apassenger** [comment]
There was a different charachter in my seed file and I removed it but I still have the same message "Aborted (core dumped)"
Here is my seed and source file
[seed2.txt](https://github.com/jdbancal/libtrevisan/files/5665266/seed2.txt)
[source.txt](https://github.com/jdbancal/libtrevisan/files/5665267/source.txt)
And here is my code script 

`./extractor  -v --Blk_Design --bitext rsh --eps 5.13135518e-18 --alpha 0.16 --weakdes gfp --outputsize 1500 --inputsize 15000 --seed seed2.txt --input source.txt --output_file output.txt 

`

**Comment by apassenger** [comment]
Any update for this issue?
Thank you !

**Comment by jdbancal** [comment]
Have you tried compiling the binary (and libraries) again from scratch on a new machine?

**Comment by apassenger** [comment]
Unfortunately, I dont have other machine. Even for running this library I convert my laptop as dual operation system because I use windows...
But here is my screenshot maybe you can notice someting
![Screenshot from 2020-12-23 01-11-38](https://user-images.githubusercontent.com/25195538/102944707-d949d600-44bb-11eb-8363-de314d782474.png)
And depends on ly output file size sometimes I am getting first out of range and then aborted dump. I think it is related to my parameter but I could not understand why
![Screenshot from 2020-12-23 01-33-09](https://user-images.githubusercontent.com/25195538/102945775-0e0b5c80-44bf-11eb-961e-cbf6e3781f26.png)
Or if it is possible and if you still have the program, can you send me  extractor as an email?
Best regards
Thanks for your helps

**Comment by jdbancal** [comment]
This kind of error can happen if something went fishy in the linking to some of the libraries, at least it happened to me sometimes when compiling a new program for the first time. To look into it, I would need to recompile things from scratch, which will not be possible before some time next year. If you are in a hurry, you can use a simple virtual machine to have an easy and clean system to experiment with. Ubuntu virtualbox images for instance are available to download online.

**Comment by apassenger** [comment]
Thank you very much for your answer! Before installing ubuntu and converting laptop as a dual operation system, I already tried virtual machine but it was quite bad  and it always stopped 
Anyway, I will find a way because I am in a hurry and I have to do that. 
Do you still have the exe file for extractor ? Maybe I should try with that and if it is works, this means that my parameter and everything ok and then I can remove and recompile the libraries if it does not work, at least I can understand the error is my parameters and everything..(I know it should be related to compiling stage but at least I can see and be sure for the reason)
Thanks for your patience...

**Comment by jdbancal** [comment]
If the problem is in the libraries compilation, running another binary that loads the same libraries is likely to produce the same (or worse) outcome, especially if it was compiled for another version of these libraries...

**Comment by apassenger** [comment]
do you think that, it is related to structure of my files. Maybe format of the file is wrong because core dumped is related to memory lack / memory errors ...

**Comment by jdbancal** [comment]
Do you mean you tried to recompile from scratch on a new (possibly virtual) machine and got the same result?

The data files are not expected to have a lot of structure. What doesn't fit is simply ignored. You can try to put a newline character after every 80 characters and finish the file with a new line as well for niceness, but I'ld be surprised if this changed the observed behavior.
